name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Wakatime Data
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -s -G -d "api_key=$WAKATIME_API_KEY" https://wakatime.com/api/v1/users/current/summaries -o wakatime.json
          cat wakatime.json

      - name: Validate JSON
        run: |
          if ! jq empty wakatime.json; then
            echo "Invalid JSON response"
            exit 1
          fi

      - name: Update README
        run: |
          echo "Cập nhật lần cuối: $(date)" >> README.md
          echo "Thống kê Wakatime:" >> README.md
          jq -r '.data[]?.grand_total?.text // "No data"' wakatime.json >> README.md

            - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "LTPPPP"
          git config --global user.email "lamphat279@gmail.com"
          git remote set-url origin https://LTPPPP:${PAT_TOKEN}@github.com/LTPPPP/LTPPPP.git
          git add README.md
          git commit -m "Auto-update README with Wakatime [skip ci]" || echo "No changes to commit"
          git push origin main

